[ClassVersion("1"), FriendlyName("cAdministrativeTemplateSetting")]
class PshOrg_AdminTemplateSetting : OMI_BaseResource
{
[Key,ValueMap{"Machine", "User", "Administrators", "NonAdministrators"},Values{"Machine", "User", "Administrators", "NonAdministrators"}] string PolicyType;
[Key] string KeyValueName;
[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
[write] string Data[];
[write,ValueMap{"0","1","2","3","4","7","11","-1"},Values{"Unknown","String","ExpandString","Binary","DWord","MultiString","QWord","None"}] sint32 Type;
};
